---
server:
  port: 8080
  servlet:
    session:
      timeout: 9960700
spring:
  profiles: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:redblue
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate.enable_lazy_load_no_trans: true
  flyway:
    locations: ["classpath:db/migration", "classpath:db/migration-sample"]
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  thymeleaf:
    cache: false