server:
  port: 8080
  servlet:
    session:
      timeout: 9960700
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://redblue80.ipdisk.co.kr:3306/redblue?serverTimezone=UTC
    username: redblue
    password: password
  jpa:
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: validate
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    prefix: classpath:/templates
---
server:
  port: 8080
  servlet:
    session:
      timeout: 9960700
spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://redblue80.ipdisk.co.kr:3306/redblue?serverTimezone=UTC
    username: redblue
    password: password
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate.enable_lazy_load_no_trans: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  thymeleaf:
    cache: false