INSERT INTO LAW_FIRM (ID, NAME, DESCRIPTION, CREATED_AT)
VALUES ('sample-lawfirm-id', '테스트법무사', '테스트 데이터', NOW());


INSERT INTO COMPANY (ID, LAW_FIRM_ID, REGISTER_OFFICE, REGISTER_NUMBER, COMPANY_NUMBER1,
                     COMPANY_NUMBER2, COMPANY_NAME, COMPANY_SUB_NAME, COMPANY_UPDATED_AT, COMPANY_REGISTER_UPDATED_AT,
                     COMPANY_ADDRESS, COMPANY_ADDRESS_UPDATED_AT, COMPANY_ADDRESS_REGISTER_UPDATED_AT,
                     BUSINESS_TYPE, BUSINESS_CONDITION, DELIVERY_PLACE, ETC,
                     CONVERTIBLE_BOND, STOCK_PURCHASE_OPTION, COMPANY_FORMATION_AT,
                     REGISTER_RECORD_CREATE_REASON, REGISTER_RECORD_CREATE_AT, IS_HEAD_OFFICE_TRANSFER,
                     HEAD_OFFICE_TRANSFER_AT, HEAD_OFFICE_TRANSFER_REGISTER_AT, IS_DISBAND, DISBAND_AT,
                     DISBAND_REGISTER_AT, DISBAND_DEEMED_AT, IS_LIQUIDATION, LIQUIDATION_AT,
                     LIQUIDATION_REGISTER_AT, IS_REGISTER_RECORD_CLOSURE, REGISTER_RECORD_CLOSURE_AT,
                     SETTLEMENT_AT)
VALUES ('sample-company-id-01', 'sample-lawfirm-id', '고양', 41429, '285011', '0414297', '온빛전자', '온빛전자1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);