CREATE TABLE  USERS (
  ID VARCHAR(50) NOT NULL,
  LAW_FIRM_ID VARCHAR(50) NOT NULL,
  USERNAME VARCHAR(45) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) NULL,
  CREATED_AT TIMESTAMP NULL,
  PRIMARY KEY (ID)
  );